package testdb

import (
	"crypto/rand"
	"fmt"
	"math"
	"strings"
	"time"
)

// Shared fixture constants and builders (5a fixture conventions). The names
// are the generic application and namespace names the repository uses in
// docs and tests (AGENTS.md); they are obviously synthetic. The seeded
// vector space is migration 0002's single space: 1024 dimensions, cosine
// distance.
//
// Application and namespace fixtures are created through the service's own
// paths (the admin API in HTTP tests, the service functions in DB tests),
// never through harness DDL: the harness provisions only the database, the
// extension, and the roles, the same infrastructure boundary production
// has. The names and vectors below are the data those service calls carry.
//
// IDs: NewUUID is a random UUIDv7 via crypto/rand (the package-2 service
// functions that generate IDs do not exist yet in this repository state;
// when they land, fixtures that must exercise production ID generation
// switch to them). Credentials are generated by the service the same way.
// No fixture value is a secret, and none is derived from real user content.

// Seeded vector space (migration 0002). Fixture vectors must match its
// dimensionality to be storable.
const (
	// SeededSpaceID is the UUID of the seeded space.
	SeededSpaceID = "0199f31e-1000-7000-8000-000000000001"

	// SeededSpaceKey is the stable key of the seeded space.
	SeededSpaceKey = "qwen3-embedding-0.6b-1024-cosine-v1"

	// SeededSpaceDimensions is the seeded space's dimensionality.
	SeededSpaceDimensions = 1024
)

// Generic application names (the standard isolation fixture: two
// applications, each with its own namespace; application A also has a
// second namespace for the namespace-axis cases).
const (
	AppMemoryService = "memory-service"
	AppNotesService  = "notes-service"
)

// Generic namespace keys.
const (
	NamespaceProjectAlpha = "project-alpha" // application A
	NamespaceProjectBeta  = "project-beta"  // application B
	NamespaceResearch     = "research"      // application A, second namespace
)

// BasisVector returns the deterministic unit vector with a 1.0 in the i-th
// dimension and 0.0 elsewhere, for the seeded space's dimensionality. Basis
// vectors are the canonical synthetic fixture: nearest-neighbor outcomes
// are exact and stable (the cosine distance between two distinct basis
// vectors is a fixed, known value), and any vector is a non-negative
// combination of them.
//
// i must be in [0, SeededSpaceDimensions); a value outside that range is a
// programming error and panics.
func BasisVector(i int) []float32 {
	if i < 0 || i >= SeededSpaceDimensions {
		panic(fmt.Sprintf("testdb: basis vector index %d out of range [0, %d)", i, SeededSpaceDimensions))
	}
	v := make([]float32, SeededSpaceDimensions)
	v[i] = 1.0
	return v
}

// ScaledVector returns a deterministic vector whose i-th component is the
// given scale and every other component is 0.0. It is the basis vector with
// its non-zero component scaled, for distance-ranking tests (cosine
// distance to the i-th unit basis vector is independent of the scale;
// euclidean distance is a function of it).
//
// i must be in [0, SeededSpaceDimensions); a value outside that range is a
// programming error and panics.
func ScaledVector(i int, scale float32) []float32 {
	v := BasisVector(i)
	v[i] = scale
	return v
}

// UniformVector returns a deterministic all-equal vector: every component is
// the given value. For the cosine metric it is a single fixed direction;
// for euclidean it is a fixed-magnitude vector. It is a "neutral" query
// vector that is equidistant from every basis vector (cosine: an equal dot
// product with each).
func UniformVector(value float32) []float32 {
	v := make([]float32, SeededSpaceDimensions)
	for i := range v {
		v[i] = value
	}
	return v
}

// VectorEquals reports whether two vectors are element-wise equal.
func VectorEquals(a, b []float32) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// EncodeVectorText renders a float32 slice as pgvector's text form
// "[a,b,c,...]" — the codec's round-trip form (package 1, section 6). It is
// for direct-DB fixture assertions only (inserting a vector as a literal or
// parameter in a test's own SQL); the production codec is what the service
// uses on the data plane. Components are rendered with the shortest decimal
// string that round-trips to the same float32 bit pattern, comma-separated,
// wrapped in square brackets.
func EncodeVectorText(v []float32) string {
	var b strings.Builder
	b.WriteByte('[')
	for i, c := range v {
		if i > 0 {
			b.WriteByte(',')
		}
		b.WriteString(float32ToShortest(c))
	}
	b.WriteByte(']')
	return b.String()
}

// float32ToShortest renders a float32 with the shortest decimal string that
// decodes back to the identical float32 bit pattern. It promotes the float32
// to float64 losslessly and renders with %g at precision -1, the shortest
// form that uniquely identifies the float64; because that float64 is the
// exact promotion of a float32, parsing the string back to float32 recovers
// the original bits. NaN and ±Inf emit the pgvector text tokens "nan",
// "inf", "-inf".
func float32ToShortest(c float32) string {
	switch {
	case math.IsNaN(float64(c)):
		return "nan"
	case math.IsInf(float64(c), 1):
		return "inf"
	case math.IsInf(float64(c), -1):
		return "-inf"
	default:
		return fmt.Sprintf("%g", float64(c))
	}
}

// NewUUID returns a random UUIDv7 (RFC 9562) as a lowercase hyphenated
// string. It uses crypto/rand for the 122 random bits and stamps the current
// Unix-millisecond time into the 48-bit version-7 timestamp field, so the
// value is time-sortable and obviously synthetic (random, never derived
// from user content). It is the fixture ID generator until the package-2
// service ID functions exist; tests that must exercise production ID
// generation use those instead.
//
// The value is random: it is not a secret and may appear in test output.
func NewUUID() (string, error) {
	var raw [16]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", fmt.Errorf("testdb: generate fixture UUID: %w", err)
	}
	// UUIDv7: 48-bit Unix-ms timestamp | 4-bit version (0111) | 12-bit
	// rand_a | 2-bit variant (10) | 62-bit rand_b.
	ms := uint64(time.Now().UnixMilli())
	raw[0] = byte(ms >> 40)
	raw[1] = byte(ms >> 32)
	raw[2] = byte(ms >> 24)
	raw[3] = byte(ms >> 16)
	raw[4] = byte(ms >> 8)
	raw[5] = byte(ms >> 0)
	raw[6] = (raw[6] & 0x0f) | 0x70 // version 7
	raw[8] = (raw[8] & 0x3f) | 0x80 // variant 10
	return formatUUID(raw[:]), nil
}

// formatUUID renders 16 bytes as a lowercase hyphenated UUID
// (8-4-4-4-12).
func formatUUID(b []byte) string {
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// IsolationFixture is the standard two-application, two-namespace fixture
// (plus application A's second namespace) the 5b isolation matrix and the
// logging matrix consume. It carries the names and the per-application
// metadata objects; the actual rows are created through the service's own
// paths (admin API or service functions), which the matrix drives against
// the provisioned database.
//
// It is deterministic: every field is fixed, so test assertions are exact
// and re-runs observe identical data.
type IsolationFixture struct {
	// AppA and AppB are the two applications' keys.
	AppA, AppB string

	// NamespacesA is application A's namespace keys (its own, plus the
	// second namespace for the namespace-axis cases).
	NamespacesA []string

	// NamespacesB is application B's namespace keys.
	NamespacesB []string

	// MetadataA and MetadataB are the small fixed metadata objects the
	// fixtures carry, one per application, so filter tests are exact and
	// the two applications' records are distinguishable by metadata alone.
	MetadataA, MetadataB map[string]any

	// VectorsA and VectorsB are the deterministic record vectors per
	// application: basis vectors, so nearest-neighbor outcomes are exact
	// and the two applications' vectors are distinct (orthogonal)
	// directions.
	VectorsA, VectorsB []float32
}

// NewIsolationFixture returns the standard isolation fixture. The vector
// assignment is fixed: application A's records use basis vector 0,
// application B's use basis vector 1, so a search with A's vector matches
// only A's records (cosine: the two basis directions are orthogonal).
func NewIsolationFixture() *IsolationFixture {
	return &IsolationFixture{
		AppA:        AppMemoryService,
		AppB:        AppNotesService,
		NamespacesA: []string{NamespaceProjectAlpha, NamespaceResearch},
		NamespacesB: []string{NamespaceProjectBeta},
		MetadataA: map[string]any{
			"document_type": "note",
			"state":         "active",
			"service":       AppMemoryService,
		},
		MetadataB: map[string]any{
			"document_type": "note",
			"state":         "active",
			"service":       AppNotesService,
		},
		VectorsA: BasisVector(0),
		VectorsB: BasisVector(1),
	}
}

// DeterministicObjectID returns a deterministic, obviously-synthetic
// object_id for a fixture record. It is a fixed UUID-shaped string derived
// from the application key and a per-record ordinal, so it is stable across
// runs (re-runnable tests) yet unique per (app, ordinal) pair. Per-test data
// uses distinct ordinals so test functions do not collide.
//
// The value is not random (it is derived from its arguments), which is what
// makes assertions about "the same object" stable across a re-run. It is a
// UUIDv4-shaped form (version/variant bits set) so it passes any UUID
// grammar check the API performs.
func DeterministicObjectID(app string, ordinal int) string {
	var b [16]byte
	mixInto(b[:], app)
	binaryLE(int64(ordinal), b[8:16])
	b[6] = (b[6] & 0x0f) | 0x40 // version 4-shaped
	b[8] = (b[8] & 0x3f) | 0x80 // variant 10
	return formatUUID(b[:])
}

// DeterministicProjectionID is like DeterministicObjectID but carries both
// the object ordinal and the projection ordinal, so (object, projection)
// pairs are stable across runs.
func DeterministicProjectionID(app string, objectOrdinal, projectionOrdinal int) string {
	var b [16]byte
	mixInto(b[:], app)
	b[12] = byte(objectOrdinal)
	b[13] = byte(objectOrdinal >> 8)
	b[14] = byte(projectionOrdinal)
	b[15] = byte(projectionOrdinal >> 8)
	b[6] = (b[6] & 0x0f) | 0x40 // version 4-shaped
	b[8] = (b[8] & 0x3f) | 0x80 // variant 10
	return formatUUID(b[:])
}

// mixInto folds the bytes of app into dst (XOR across both 8-byte halves,
// offset by the position) so the result depends on every byte of the
// application key. The key may be longer than 8 bytes: the fold wraps
// (i%8), so every byte contributes to both halves.
func mixInto(dst []byte, app string) {
	for i, c := range []byte(app) {
		dst[i%8] ^= c
		dst[(i%8)+8] ^= c
	}
}

// binaryLE writes n little-endian into the 8-byte destination.
func binaryLE(n int64, dst []byte) {
	for i := 0; i < 8; i++ {
		dst[i] = byte(n >> (8 * i))
	}
}

// A compile-time guard: the fixture dimensionality must match the seeded
// space, so a fixture vector can never silently have the wrong dimension
// for the seeded space.
var _ = func() {
	if len(BasisVector(0)) != SeededSpaceDimensions {
		panic("testdb: fixture vector dimensionality mismatch")
	}
}
